set SPACEFISH_CHAR_SYMBOL λ
set SPACEFISH_CHAR_COLOR_FAILURE '#ffcc00'
set SPACEFISH_CHAR_COLOR_SUCCESS '#ff5500'

set SPACEFISH_VI_MODE_NORMAL ☭
set SPACEFISH_VI_MODE_INSERT 'ﭾ'
set SPACEFISH_VI_MODE_VISUAL 'ﭾ'
set SPACEFISH_VI_MODE_REPLACE_ONE 'ﭾ'
set SPACEFISH_VI_MODE_COLOR '#aa5500'
set SPACEFISH_VI_MODE_PREFIX ''

set SPACEFISH_BATTERY_SHOW always
set SPACEFISH_BATTERY_PREFIX ' '
set SPACEFISH_BATTERY_SUFFIX ' '

set SPACEFISH_USER_PREFIX ''
set SPACEFISH_HOST_PREFIX ''

set SPACEFISH_TIME_COLOR '#003300'
set SPACEFISH_TIME_SHOW true
set SPACEFISH_TIME_PREFIX ''
set SPACEFISH_TIME_SUFFIX ''

set SPACEFISH_PROMPT_ORDER git_commit git_branch line_sep \
  user dir host package node ruby golang php rust haskell julia docker aws conda pyenv dotnet kubecontext line_sep \
  vi_mode jobs exit_code exec_time char
set SPACEFISH_RPROMPT_ORDER git_status time battery

set SPACEFISH_GIT_PREFIX ''
set SPACEFISH_GIT_COMMIT_PREFIX ' '
set SPACEFISH_GIT_COMMIT_SUFFIX ' '
set SPACEFISH_GIT_COMMIT_SHOW true
set SPACEFISH_GIT_BRANCH_PREFIX ' '
set SPACEFISH_GIT_BRANCH_SUFFIX ' '
set SPACEFISH_GIT_STATUS_PREFIX ''
set SPACEFISH_GIT_STATUS_SUFFIX ''
set SPACEFISH_GIT_STATUS_ADDED '✚ '
set SPACEFISH_GIT_STATUS_AHEAD ' '
set SPACEFISH_GIT_STATUS_BEHIND ' '
set SPACEFISH_GIT_STATUS_DELETED '✖ '
set SPACEFISH_GIT_STATUS_DIVERGED ' '
set SPACEFISH_GIT_STATUS_MODIFIED '✱ '
set SPACEFISH_GIT_STATUS_RENAMED '➜ '
set SPACEFISH_GIT_STATUS_STASHED 'ﰤ'
set SPACEFISH_GIT_STATUS_UNMERGED ' '
set SPACEFISH_GIT_STATUS_UNTRACKED ' '
set SPACEFISH_GIT_SYMBOL ''
set SPACEFISH_GIT_STATUS_COLOR '#990000'

set SPACEFISH_KUBECONTEXT_SHOW false

set SPACEFISH_DOCKER_PREFIX ' '
set SPACEFISH_DOCKER_SYMBOL ''

set SPACEFISH_PHP_PREFIX ' '
set SPACEFISH_PHP_SYMBOL ''

set SPACEFISH_NODE_PREFIX ' '
set SPACEFISH_NODE_SYMBOL ''

set SPACEFISH_PYENV_PREFIX ' '
set SPACEFISH_PYENV_SYMBOL ''

set SPACEFISH_RUBY_PREFIX ' '
set SPACEFISH_RUBY_SYMBOL ''

set SPACEFISH_DIR_PREFIX ''
set SPACEFISH_DIR_TRUNC 0
